Unneeded `return` statement
Fixing the following issue after switching to stable rust version:

error: unneeded `return` statement
   --> spdmlib/src/responder/finish_rsp.rs:375:13
    |
375 |             return (Err(e), Some(writer.used_slice()));

Signed-off-by: Zbigniew Lukwinski <zbigniew.lukwinski@intel.com>