Lifetime 'a could be elided
Fixing the following issue after switching to stable rust version:

error: the following explicit lifetimes could be elided: 'a
  --> codec/src/codec.rs:19:6
   |
19 | impl<'a> Reader<'a> {
   |      ^^         ^^

Signed-off-by: Zbigniew Lukwinski <zbigniew.lukwinski@intel.com>