`#![feature]` may not be used on the stable release channel
Fixing the following issue after switching to stable rust version:

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> spdmlib/src/lib.rs:7:1
  |
7 | #![feature(stmt_expr_attributes)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> spdmlib/src/lib.rs:8:1
  |
8 | #![feature(try_trait_v2)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^

Signed-off-by: Zbigniew Lukwinski <zbigniew.lukwinski@intel.com>