No empty line after doc comment
Fixing the following issue after switching to stable rust version:

error: empty line after doc comment
  --> spdmlib/src/error.rs:10:1
   |
10 | / /// Reference: https://github.com/DMTF/libspdm/blob/main/include/library/spdm_return_status.h

Signed-off-by: Zbigniew Lukwinski <zbigniew.lukwinski@intel.com>