'FromResidual' and 'Try' comes from unstable library feature 'try_trait_v2'
Fixing the following issue after switching to stable rust version:

error[E0658]: use of unstable library feature 'try_trait_v2'
 --> spdmlib/src/error.rs:8:24
  |
8 |     ops::{ControlFlow, FromResidual, Try},
  |                        ^^^^^^^^^^^^
  |
  = note: see issue #84277 <https://github.com/rust-lang/rust/issues/84277> for more information

error[E0658]: use of unstable library feature 'try_trait_v2'
 --> spdmlib/src/error.rs:8:38
  |
8 |     ops::{ControlFlow, FromResidual, Try},

Signed-off-by: Zbigniew Lukwinski <zbigniew.lukwinski@intel.com>